sudo: required
services:
  - docker

before_install:
  - docker build -t saharnab99/multidock-cicd -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true saharnab99/multidock-cicd npm run test -- --coverage

after_success:
  - docker build -t saharnab99/multidock-client ./client
  - docker build -t saharnab99/multidock-nginx ./nginx
  - docker build -t saharnab99/multidock-server ./server
  - docker build -t saharnab99/multidock-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push saharnab99/multidock-client
  - docker push saharnab99/multidock-nginx
  - docker push saharnab99/multidock-server
  - docker push saharnab99/multidock-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "ap-south-1"
#   app: "docker-aws"
#   env: "DockerAws-env"
#   bucket_name: "elasticbeanstalk-ap-south-1-024497252280"
#   bucket_path: "multidock"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
